### ISSUE TITLE
Module broken on 7.9.1 ?

### ISSUE THREAD

**Issue by Hostground** [gg-software/messagebird-whmcs-module#2] opened 2020-01-29 19:55 UTC
I'm getting the error page:

Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

Is there something wrong with this module for this version?

**Comment by jake-walker** [comment] 2020-01-29 22:07
Hi @Hostground,

Unfortunately this plugin was written 2 years ago now so it might be that it doesn't work with newer versions of WHMCS. From your error it sounds like an error that could be caused by this plugin that is preventing the page from loading.

If I remember correctly, the latest version (in the master branch) should be the one that we used in our production setup and so should work correctly, but that was a couple of years ago so I can't remember fully.

I don't have access to a WHMCS setup for testing and developing the plugin anymore and also I'm not really developing it anymore. If you could provide some logs I might be able to narrow down the problem for you or create a quick fix.

Jake

**Comment by jake-walker** [comment] 2020-02-09 13:51
I'm going to close this issue now as there has been no reply for 10 days. Feel free to open this issue again though 🙂.

**Closed by jake-walker** 2020-02-09 13:51 UTC
Labels: help wanted
